### ISSUE TITLE
Run in same user context as open browser

### ISSUE THREAD

**Issue by keda82** [Strange-Panda/jitsi-stress-test#1]
Great tool!

Is there any way to get the tool to run in an in the same context as an already opened Google Chrome browser? This to make session and authentication cookies available to bypass login to Jitsi?

**Comment by brommet87** [comment]
Thats not possible. But you can use advanced session management: 

https://medium.com/@ghulammustafapy/efficient-login-session-management-in-selenium-python-save-and-reuse-credentials-for-browser-7aa21b32df63
